# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'build/dist/designer/settings_global.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(421, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.sb_after = QtWidgets.QSpinBox(self.tab)
        self.sb_after.setMinimum(-1)
        self.sb_after.setObjectName("sb_after")
        self.gridLayout_3.addWidget(self.sb_after, 2, 2, 1, 1)
        self.sb_cloze = QtWidgets.QSpinBox(self.tab)
        self.sb_cloze.setMinimum(1)
        self.sb_cloze.setObjectName("sb_cloze")
        self.gridLayout_3.addWidget(self.sb_cloze, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 2, 1, 1)
        self.sb_before = QtWidgets.QSpinBox(self.tab)
        self.sb_before.setMinimum(-1)
        self.sb_before.setObjectName("sb_before")
        self.gridLayout_3.addWidget(self.sb_before, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 0, 1, 3)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cb_ncf = QtWidgets.QCheckBox(self.tab)
        self.cb_ncf.setObjectName("cb_ncf")
        self.gridLayout_2.addWidget(self.cb_ncf, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 2)
        self.cb_ncl = QtWidgets.QCheckBox(self.tab)
        self.cb_ncl.setObjectName("cb_ncl")
        self.gridLayout_2.addWidget(self.cb_ncl, 2, 0, 1, 1)
        self.cb_incr = QtWidgets.QCheckBox(self.tab)
        self.cb_incr.setObjectName("cb_incr")
        self.gridLayout_2.addWidget(self.cb_incr, 1, 1, 1, 1)
        self.cb_gfc = QtWidgets.QCheckBox(self.tab)
        self.cb_gfc.setObjectName("cb_gfc")
        self.gridLayout_2.addWidget(self.cb_gfc, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cb_ns_new = QtWidgets.QCheckBox(self.tab_2)
        self.cb_ns_new.setObjectName("cb_ns_new")
        self.gridLayout_4.addWidget(self.cb_ns_new, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.cb_ns_rev = QtWidgets.QCheckBox(self.tab_2)
        self.cb_ns_rev.setObjectName("cb_ns_rev")
        self.gridLayout_4.addWidget(self.cb_ns_rev, 2, 0, 1, 1)
        self.cb_sfc = QtWidgets.QCheckBox(self.tab_2)
        self.cb_sfc.setObjectName("cb_sfc")
        self.gridLayout_4.addWidget(self.cb_sfc, 3, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.le_fl = QtWidgets.QLineEdit(self.tab_2)
        self.le_fl.setObjectName("le_fl")
        self.gridLayout.addWidget(self.le_fl, 4, 2, 1, 1)
        self.le_model = QtWidgets.QLineEdit(self.tab_2)
        self.le_model.setReadOnly(False)
        self.le_model.setObjectName("le_model")
        self.gridLayout.addWidget(self.le_model, 6, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 3)
        self.le_st = QtWidgets.QLineEdit(self.tab_2)
        self.le_st.setObjectName("le_st")
        self.gridLayout.addWidget(self.le_st, 3, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 2)
        self.le_og = QtWidgets.QLineEdit(self.tab_2)
        self.le_og.setObjectName("le_og")
        self.gridLayout.addWidget(self.le_og, 1, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 5, 0, 1, 3)
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 6, 0, 1, 2)
        self.verticalLayout_3.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.htmlAbout = QtWidgets.QTextBrowser(self.tab_3)
        self.htmlAbout.setOpenExternalLinks(True)
        self.htmlAbout.setObjectName("htmlAbout")
        self.verticalLayout_4.addWidget(self.htmlAbout)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tabWidget, self.sb_before)
        Dialog.setTabOrder(self.sb_before, self.sb_cloze)
        Dialog.setTabOrder(self.sb_cloze, self.sb_after)
        Dialog.setTabOrder(self.sb_after, self.cb_ncf)
        Dialog.setTabOrder(self.cb_ncf, self.cb_ncl)
        Dialog.setTabOrder(self.cb_ncl, self.cb_incr)
        Dialog.setTabOrder(self.cb_incr, self.cb_gfc)
        Dialog.setTabOrder(self.cb_gfc, self.cb_ns_new)
        Dialog.setTabOrder(self.cb_ns_new, self.cb_ns_rev)
        Dialog.setTabOrder(self.cb_ns_rev, self.cb_sfc)
        Dialog.setTabOrder(self.cb_sfc, self.le_og)
        Dialog.setTabOrder(self.le_og, self.le_st)
        Dialog.setTabOrder(self.le_st, self.le_fl)
        Dialog.setTabOrder(self.le_fl, self.le_model)
        Dialog.setTabOrder(self.le_model, self.buttonBox)
        Dialog.setTabOrder(self.buttonBox, self.htmlAbout)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Cloze Overlapper Options"))
        self.sb_after.setToolTip(_translate("Dialog", "Number of context cues after the prompt.<br>Set to -1/\'all\' to show all following items as context"))
        self.sb_after.setSpecialValueText(_translate("Dialog", "all"))
        self.sb_cloze.setToolTip(_translate("Dialog", "Number of items to prompt for per card"))
        self.label_12.setText(_translate("Dialog", "Context Before"))
        self.label_13.setText(_translate("Dialog", "Cloze Prompts"))
        self.label_14.setText(_translate("Dialog", "Context After"))
        self.sb_before.setToolTip(_translate("Dialog", "Number of context cues before the prompt.<br>Set to -1/\'all\' to show all previous items as context"))
        self.sb_before.setSpecialValueText(_translate("Dialog", "all"))
        self.label_11.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Default Context Cues and Prompts</span></p></body></html>"))
        self.cb_ncf.setToolTip(_translate("Dialog", "Don\'t provide any context cues for first cloze item"))
        self.cb_ncf.setText(_translate("Dialog", "No cues for first item"))
        self.label_10.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Other Cloze Generation Settings</span></p></body></html>"))
        self.cb_ncl.setToolTip(_translate("Dialog", "Don\'t provide any context cues for last cloze item"))
        self.cb_ncl.setText(_translate("Dialog", "No cues for last item"))
        self.cb_incr.setToolTip(_translate("Dialog", "For notes that have multiple clozes revealed per card,<br>gradually build up to full reveal count at the start,<br>and vice-versa in the end"))
        self.cb_incr.setText(_translate("Dialog", "Gradual build-up/-down"))
        self.cb_gfc.setToolTip(_translate("Dialog", "Disable cards that prompt you for all items at once"))
        self.cb_gfc.setText(_translate("Dialog", "Don\'t generate full cloze"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Cloze Generation"))
        self.cb_ns_new.setToolTip(_translate("Dialog", "Disables sibling-burying for cards generated by the add-on,<br>overriding whatever deck options might be set.<br>Only works on Anki desktop"))
        self.cb_ns_new.setText(_translate("Dialog", "Override sibling-spacing for new overlapping clozes"))
        self.label_4.setText(_translate("Dialog", "<b>Scheduling</b>"))
        self.cb_ns_rev.setToolTip(_translate("Dialog", "Disables sibling-burying for cards generated by the add-on,<br>overriding whatever deck options might be set.<br>Only works on Anki desktop"))
        self.cb_ns_rev.setText(_translate("Dialog", "Override sibling-spacing for overlapping cloze reviews"))
        self.cb_sfc.setText(_translate("Dialog", "Automatically suspend full cloze cards initially"))
        self.le_fl.setToolTip(_translate("Dialog", "These fields can only be renamed through this dialog"))
        self.le_model.setToolTip(_translate("Dialog", "Comma-separated list of note types the add-on should be active on"))
        self.label_2.setText(_translate("Dialog", "<b>Field Names</b>"))
        self.le_st.setToolTip(_translate("Dialog", "These fields can only be renamed through this dialog"))
        self.label_7.setText(_translate("Dialog", "Settings"))
        self.label_3.setText(_translate("Dialog", "Original"))
        self.le_og.setToolTip(_translate("Dialog", "These fields can only be renamed through this dialog"))
        self.label_9.setText(_translate("Dialog", "Full"))
        self.label_15.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Overlapping Cloze Note Types</span></p></body></html>"))
        self.label_16.setText(_translate("Dialog", "Names"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "General"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "About"))

